### ISSUE TITLE
SDXL support

### ISSUE THREAD

**Issue by lendrick** [ljleb/sd-webui-freeu#1]
It doesn't look like it's running for SDXL.  Any chance it could support that as well?

**Comment by lendrick** [comment]
Also, thanks for doing this so quickly! :)

**Comment by lendrick** [comment]
Here's a quick and dirty patch.  It duplicates a ton of code, but it works:

https://pastebin.com/7E57HEZp

**Comment by ljleb** [comment]
Thanks, working on it. Should push a fix shortly.

**Comment by ljleb** [comment]
I'm not happy with all that copy pasted code but I guess it's not really practical to monkey patch it either. There may be a better solution but we'll go with that for now
