### ISSUE TITLE
FreeU doesn't work when using with ControlNet

### ISSUE THREAD

**Issue by MichaelWang1995** [ljleb/sd-webui-freeu#11]
When using with Controlnet (any control type), FreeU will have not effect.
Control net ver: 1.1.410
No error or message in command prompt.

Works fine with all other extensions I have.

**Comment by ljleb** [comment]
Controlnet overrides the unet forward function, we need to patch their unet as well. Having all these unet functions to copy paste is no good, we need to find a solution to only patch the `torch.cat` in the decoder block for-loop.
