### ISSUE TITLE
generation failed on AMD directml

### ISSUE THREAD

**Issue by silvertuanzi** [ljleb/sd-webui-freeu#21]
enable freeu and click generate, then: 
>   0%|                                                                                           | 0/20 [00:00<?, ?it/s]
> [F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_util.cc:118] Invalid or unsupported data type.
> press any key to continue... 

the whole Stable Diffusion process exits directly.

using: https://github.com/lshqqytiger/stable-diffusion-webui-directml
commit: 7b0b721

**Comment by ljleb** [comment]
Yes, it is a known issue. I was looking for how to solve this and I just found the solution. Will push a fix shortly.

**Comment by ljleb** [comment]
dml should do the fft on cpu now. Note that this will result in an expected slower generation time when the extension is enabled. see #16
