### ISSUE TITLE
What is the difference between version1 and version2?

### ISSUE THREAD

**Issue by ramge132** [ljleb/sd-webui-freeu#41]
At some point, version 2 became available, what's the difference?

**Comment by ljleb** [comment]
In version 2 the effective backbone scale is more dynamic. In each intermediate unet latent, the distance between any feature vector and the mean is used to determine how much the backbone scale should be reduced. You can check the updated paper for a more precise explanation.

**Comment by ljleb** [comment]
The recommended presets are not the same exactly for v1 vs v2. I'm waiting for the official code to receive an update before updating the code here.
