### ISSUE TITLE
Enhance documentation in the readme

### ISSUE THREAD

**Issue by 9wow** [ljleb/sd-webui-freeu#44]
- What is B1 B2 S1 S2? 
- What do the letters B & S mean?
- What does B1 B2 S1 S2 do?
- What do the number values mean?
- What effect does each parameter have on the output?
- What effect does each parameter have depending on the set value?
- Should they all be used at a value above 0?
- Why do the parameters have different maximum values?

**Comment by ljleb** [comment]
In the readme of this repo, I vaguely explain a little bit what the controls do. They are not abbreviations, although I concede that it does not make an effort to explain anything further.

You might be interested in reading the paper from the original authors. If anyone wants to contribute to the repository to enhance readability, PRs are welcome.

**Comment by ljleb** [comment]
After trying out forge, I realize you might have intended to open an issue in the official forge repo. To put it clearly, this extension has nothing to do with forge. This is not the code forge uses, it has a completely different purpose. This is an extension for a1111 webui, not forge. In a1111 webui, freeu isn't builtin, however in forge it is.
