### ISSUE TITLE
Doesnt work with newest version of Forge

### ISSUE THREAD

**Issue by PixelClassicist** [ljleb/sd-webui-freeu#49]
This extension broke after the major new update of Forge, would love to use it again, as I prefer it to the integrated version

**Comment by irarayzelji2002** [comment]
same issue for me

**Comment by ljleb** [comment]
I am not using forge personally, and forge already has a module for freeu. For these reasons, I am not planning to add support for forge.

I am open to contributions if this is something you are interested in. Alternatively, I think forking this repo for exclusive forge support would make things much easier to implement, and it would make sense as forge is starting to be quite a different code base from a1111 webui.
