### ISSUE TITLE
presets.json

### ISSUE THREAD

**Issue by 9wow** [ljleb/sd-webui-freeu#51]
Thank you for this beautiful extension.

Not really an issue, more so a question/request.
Can the presets.json be changed so that presets are separated by line instead of every single preset being saved on the same single line? (One preset per line).
Or maybe something like [https://imgur.com/a/FUcdlxg](url) which instead separates each perameter by line?

Because at the moment its practically _impossible_ to manage.

**Comment by ljleb** [comment]
That's fair. The file was intended to be managed by the extension, but no harm in pretty printing.

**Comment by ljleb** [comment]
The save button should pretty print to presets.json now instead of all on the same line.
